import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title:"Services — TimelessHQ" };
const packages=[
  { number:"01", title:"Product foundation", people:"Nafis · Mahi · Sami", body:"For a product that needs its application, API, and data model considered as one system.", includes:["Web application engineering","API and backend development","Database and deployment foundations"] },
  { number:"02", title:"Interface and frontend build", people:"Efty · Saiem · Cala", body:"For teams that need a responsive, carefully implemented interface built with a product mindset.", includes:["Frontend implementation","Responsive interface systems","Performance-minded delivery"] },
  { number:"03", title:"Security audit & penetration test", people:"Sadman", body:"For a practical view of where a system is exposed and what to address first.", includes:["Scoped security assessment","Web application penetration testing","Clear findings and remediation priorities"] }
];
export default function ServicesPage(){return <main className="wrap py-16 sm:py-24"><p className="eyebrow">How we help</p><h1 className="display mt-3 max-w-3xl text-5xl sm:text-6xl">The right specialists at the right point in the mechanism.</h1><p className="mt-6 max-w-2xl leading-7 text-[#8B93A7]">Each engagement is shaped around the work at hand. These are useful starting points, not rigid boxes.</p><div className="mt-16">{packages.map(item=><article className="grid border-t rule py-8 lg:grid-cols-[120px_1fr_1fr] lg:gap-10" key={item.number}><p className="text-[#C6A15B]">{item.number}</p><div><h2 className="display text-3xl">{item.title}</h2><p className="mt-2 text-sm text-[#8B93A7]">{item.people}</p><p className="mt-5 max-w-md leading-7 text-[#8B93A7]">{item.body}</p></div><ul className="mt-6 space-y-3 border-l rule pl-5 text-sm text-[#8B93A7] lg:mt-0">{item.includes.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><section className="mt-8 border-y rule bg-[#161d2c] px-6 py-10 sm:px-10"><h2 className="display text-3xl">Not sure where to begin?</h2><p className="mt-3 max-w-xl text-[#8B93A7]">Send the brief as it stands. We’ll identify a sensible first engagement.</p><Link className="link mt-5 inline-block" href="/contact">Discuss your project</Link></section></main>}
